package com.rentalin.core.designsystem.theme

import androidx.compose.ui.graphics.Color

val RentalInPrimary = Color(0xFF10466F)
val RentalInPrimaryContainer = Color(0xFF2F5E88)
val RentalInPrimaryFixed = Color(0xFFCFE5FF)
val RentalInPrimaryFixedDim = Color(0xFF9ECBFA)
val RentalInOnPrimary = Color(0xFFFFFFFF)
val RentalInOnPrimaryContainer = Color(0xFFB2D6FF)
val RentalInOnPrimaryFixed = Color(0xFF001D34)
val RentalInOnPrimaryFixedVariant = Color(0xFF154A73)

val RentalInSecondary = Color(0xFF506072)
val RentalInSecondaryContainer = Color(0xFFD3E4FA)
val RentalInOnSecondary = Color(0xFFFFFFFF)
val RentalInOnSecondaryContainer = Color(0xFF566678)

val RentalInTertiary = Color(0xFF5B3E00)
val RentalInTertiaryContainer = Color(0xFF78540C)
val RentalInTertiaryFixed = Color(0xFFFFDEAD)
val RentalInTertiaryFixedDim = Color(0xFFF0BF6F)
val RentalInOnTertiary = Color(0xFFFFFFFF)
val RentalInOnTertiaryContainer = Color(0xFFFDCB7A)
val RentalInOnTertiaryFixed = Color(0xFF281900)
val RentalInOnTertiaryFixedVariant = Color(0xFF604100)

val RentalInBackground = Color(0xFFF9F9FD)
val RentalInOnBackground = Color(0xFF1A1C1F)
val RentalInSurface = Color(0xFFF9F9FD)
val RentalInSurfaceBright = Color(0xFFF9F9FD)
val RentalInSurfaceDim = Color(0xFFD9DADE)
val RentalInSurfaceContainerLowest = Color(0xFFFFFFFF)
val RentalInSurfaceContainerLow = Color(0xFFF3F3F7)
val RentalInSurfaceContainer = Color(0xFFEDEDF1)
val RentalInSurfaceContainerHigh = Color(0xFFE8E8EC)
val RentalInSurfaceContainerHighest = Color(0xFFE2E2E6)
val RentalInSurfaceVariant = Color(0xFFE2E2E6)
val RentalInOnSurface = Color(0xFF1A1C1F)
val RentalInOnSurfaceVariant = Color(0xFF42474E)
val RentalInInverseSurface = Color(0xFF2E3034)
val RentalInInverseOnSurface = Color(0xFFF0F0F4)
val RentalInInversePrimary = Color(0xFF9ECBFA)

val RentalInOutline = Color(0xFF72777F)
val RentalInOutlineVariant = Color(0xFFC2C7CF)
val RentalInSurfaceTint = Color(0xFF33628C)

val RentalInError = Color(0xFFBA1A1A)
val RentalInErrorContainer = Color(0xFFFFDAD6)
val RentalInOnError = Color(0xFFFFFFFF)
val RentalInOnErrorContainer = Color(0xFF93000A)

val RentalInSuccess = Color(0xFF10B981)
val RentalInSuccessContainer = Color(0xFFECFDF5)
val RentalInWarning = Color(0xFFF59E0B)
val RentalInWarningContainer = Color(0xFFFFFBEA)
val RentalInMaintenance = Color(0xFF64748B)
val RentalInMaintenanceContainer = Color(0xFFF1F5F9)
val RentalInLost = Color(0xFFEF4444)
val RentalInLostContainer = Color(0xFFFEF2F2)
val RentalInBlueStatus = Color(0xFF3B82F6)
val RentalInBlueStatusContainer = Color(0xFFEFF6FF)
